server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/accounts/**
          filters:
            - name: JwtAuthFilter

        - id: transaction-service
          uri: http://localhost:8083
          predicates:
            - Path=/transactions/**
          filters:
            - name: JwtAuthFilter